// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  accountId: __t.string(),
  collectionId: __t.string(),
  scryfallId: __t.string(),
  oracleId: __t.string(),
  name: __t.string(),
  setCode: __t.string(),
  imageUri: __t.string(),
  isFoil: __t.bool(),
  condition: __t.string(),
  quantity: __t.u32(),
};
