// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  compositeId: __t.string().primaryKey().name("composite_id"),
  collectionId: __t.string().name("collection_id"),
  scryfallId: __t.string().name("scryfall_id"),
  oracleId: __t.string().name("oracle_id"),
  name: __t.string(),
  setCode: __t.string().name("set_code"),
  imageUri: __t.string().name("image_uri"),
  quantity: __t.u32(),
  isFoil: __t.bool().name("is_foil"),
  condition: __t.string(),
  notes: __t.string(),
  addedAt: __t.u64().name("added_at"),
  updatedAt: __t.u64().name("updated_at"),
});
