// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  entryId: __t.string().primaryKey().name("entry_id"),
  deckId: __t.string().name("deck_id"),
  ownerId: __t.string().name("owner_id"),
  game: __t.string(),
  catalogCardId: __t.string().name("catalog_card_id"),
  canonicalCardId: __t.string().name("canonical_card_id"),
  name: __t.string(),
  setCode: __t.string().name("set_code"),
  imageUri: __t.string().name("image_uri"),
  quantity: __t.u32(),
  role: __t.string(),
  addedAt: __t.u64().name("added_at"),
  updatedAt: __t.u64().name("updated_at"),
});
