// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  artifactId: __t.string(),
  sessionId: __t.string(),
  originalObjectKey: __t.string(),
  normalizedObjectKey: __t.string(),
  qualityScore: __t.u32(),
  embeddingModelVersion: __t.string(),
  ocrModelVersion: __t.string(),
  status: __t.string(),
  ocrName: __t.option(__t.string()),
  ocrSetCode: __t.option(__t.string()),
  ocrCollectorNumber: __t.option(__t.string()),
  candidateJson: __t.string(),
};
