// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  ownerId: __t.string().name("owner_id"),
  originalObjectKey: __t.string().name("original_object_key"),
  normalizedObjectKey: __t.string().name("normalized_object_key"),
  qualityScore: __t.u32().name("quality_score"),
  embeddingModelVersion: __t.string().name("embedding_model_version"),
  ocrModelVersion: __t.string().name("ocr_model_version"),
  status: __t.string(),
  ocrName: __t.option(__t.string()).name("ocr_name"),
  ocrSetCode: __t.option(__t.string()).name("ocr_set_code"),
  ocrCollectorNumber: __t.option(__t.string()).name("ocr_collector_number"),
  candidateJson: __t.string().name("candidate_json"),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
