// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  sessionId: __t.string().name("session_id"),
  scanArtifactId: __t.string().name("scan_artifact_id"),
  ownerId: __t.string().name("owner_id"),
  catalogCardId: __t.string().name("catalog_card_id"),
  canonicalCardId: __t.string().name("canonical_card_id"),
  oracleId: __t.string().name("oracle_id"),
  name: __t.string(),
  setCode: __t.string().name("set_code"),
  collectorNumber: __t.string().name("collector_number"),
  imageUri: __t.string().name("image_uri"),
  similarityScore: __t.u32().name("similarity_score"),
  ocrScore: __t.u32().name("ocr_score"),
  finalScore: __t.u32().name("final_score"),
  matchReason: __t.string().name("match_reason"),
  finish: __t.string(),
  condition: __t.string(),
  quantity: __t.u32(),
  createdAt: __t.u64().name("created_at"),
  updatedAt: __t.u64().name("updated_at"),
});
