// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Collection = __t.object("Collection", {
  id: __t.string(),
  ownerId: __t.string(),
  name: __t.string(),
  description: __t.string(),
  createdAt: __t.u64(),
});
export type Collection = __Infer<typeof Collection>;

export const CollectionCard = __t.object("CollectionCard", {
  compositeId: __t.string(),
  collectionId: __t.string(),
  scryfallId: __t.string(),
  oracleId: __t.string(),
  name: __t.string(),
  setCode: __t.string(),
  imageUri: __t.string(),
  quantity: __t.u32(),
  isFoil: __t.bool(),
  condition: __t.string(),
  notes: __t.string(),
  addedAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type CollectionCard = __Infer<typeof CollectionCard>;

export const ServerConfig = __t.object("ServerConfig", {
  key: __t.string(),
  value: __t.string(),
});
export type ServerConfig = __Infer<typeof ServerConfig>;

export const UserProfile = __t.object("UserProfile", {
  accountId: __t.string(),
  username: __t.string(),
  email: __t.string(),
  lastSeen: __t.u64(),
});
export type UserProfile = __Infer<typeof UserProfile>;

