// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Deck = __t.object("Deck", {
  id: __t.string(),
  ownerId: __t.string(),
  game: __t.string(),
  name: __t.string(),
  description: __t.string(),
  format: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Deck = __Infer<typeof Deck>;

export const DeckCard = __t.object("DeckCard", {
  entryId: __t.string(),
  deckId: __t.string(),
  ownerId: __t.string(),
  game: __t.string(),
  catalogCardId: __t.string(),
  canonicalCardId: __t.string(),
  name: __t.string(),
  setCode: __t.string(),
  imageUri: __t.string(),
  quantity: __t.u32(),
  role: __t.string(),
  addedAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type DeckCard = __Infer<typeof DeckCard>;

export const Inventory = __t.object("Inventory", {
  id: __t.string(),
  ownerId: __t.string(),
  game: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Inventory = __Infer<typeof Inventory>;

export const InventoryCard = __t.object("InventoryCard", {
  entryId: __t.string(),
  inventoryId: __t.string(),
  ownerId: __t.string(),
  game: __t.string(),
  catalogCardId: __t.string(),
  canonicalCardId: __t.string(),
  name: __t.string(),
  setCode: __t.string(),
  imageUri: __t.string(),
  quantity: __t.u32(),
  finish: __t.string(),
  condition: __t.string(),
  notes: __t.string(),
  spellbookPosition: __t.u32(),
  addedAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type InventoryCard = __Infer<typeof InventoryCard>;

export const ServerConfig = __t.object("ServerConfig", {
  key: __t.string(),
  value: __t.string(),
});
export type ServerConfig = __Infer<typeof ServerConfig>;

export const UserProfile = __t.object("UserProfile", {
  accountId: __t.string(),
  username: __t.string(),
  email: __t.string(),
  lastSeen: __t.u64(),
});
export type UserProfile = __Infer<typeof UserProfile>;

