// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const BatchInventoryItem = __t.object("BatchInventoryItem", {
  catalogCardId: __t.string(),
  canonicalCardId: __t.string(),
  name: __t.string(),
  setCode: __t.string(),
  imageUri: __t.string(),
  finish: __t.string(),
  condition: __t.string(),
  quantity: __t.u32(),
});
export type BatchInventoryItem = __Infer<typeof BatchInventoryItem>;

export const Deck = __t.object("Deck", {
  id: __t.string(),
  ownerId: __t.string(),
  game: __t.string(),
  name: __t.string(),
  description: __t.string(),
  format: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Deck = __Infer<typeof Deck>;

export const DeckCard = __t.object("DeckCard", {
  entryId: __t.string(),
  deckId: __t.string(),
  ownerId: __t.string(),
  game: __t.string(),
  catalogCardId: __t.string(),
  canonicalCardId: __t.string(),
  name: __t.string(),
  setCode: __t.string(),
  imageUri: __t.string(),
  quantity: __t.u32(),
  role: __t.string(),
  addedAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type DeckCard = __Infer<typeof DeckCard>;

export const Inventory = __t.object("Inventory", {
  id: __t.string(),
  ownerId: __t.string(),
  game: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type Inventory = __Infer<typeof Inventory>;

export const InventoryCard = __t.object("InventoryCard", {
  entryId: __t.string(),
  inventoryId: __t.string(),
  ownerId: __t.string(),
  game: __t.string(),
  catalogCardId: __t.string(),
  canonicalCardId: __t.string(),
  name: __t.string(),
  setCode: __t.string(),
  imageUri: __t.string(),
  quantity: __t.u32(),
  finish: __t.string(),
  condition: __t.string(),
  notes: __t.string(),
  spellbookPosition: __t.u32(),
  addedAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type InventoryCard = __Infer<typeof InventoryCard>;

export const InventoryMutationRequest = __t.object("InventoryMutationRequest", {
  requestId: __t.string(),
  ownerId: __t.string(),
  source: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type InventoryMutationRequest = __Infer<typeof InventoryMutationRequest>;

export const ScanArtifact = __t.object("ScanArtifact", {
  id: __t.string(),
  sessionId: __t.string(),
  ownerId: __t.string(),
  originalObjectKey: __t.string(),
  normalizedObjectKey: __t.string(),
  qualityScore: __t.u32(),
  embeddingModelVersion: __t.string(),
  ocrModelVersion: __t.string(),
  status: __t.string(),
  ocrName: __t.option(__t.string()),
  ocrSetCode: __t.option(__t.string()),
  ocrCollectorNumber: __t.option(__t.string()),
  candidateJson: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ScanArtifact = __Infer<typeof ScanArtifact>;

export const ScanReviewItem = __t.object("ScanReviewItem", {
  id: __t.string(),
  sessionId: __t.string(),
  scanArtifactId: __t.string(),
  ownerId: __t.string(),
  catalogCardId: __t.string(),
  canonicalCardId: __t.string(),
  oracleId: __t.string(),
  name: __t.string(),
  setCode: __t.string(),
  collectorNumber: __t.string(),
  imageUri: __t.string(),
  similarityScore: __t.u32(),
  ocrScore: __t.u32(),
  finalScore: __t.u32(),
  matchReason: __t.string(),
  finish: __t.string(),
  condition: __t.string(),
  quantity: __t.u32(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ScanReviewItem = __Infer<typeof ScanReviewItem>;

export const ScanSession = __t.object("ScanSession", {
  id: __t.string(),
  ownerId: __t.string(),
  game: __t.string(),
  status: __t.string(),
  createdAt: __t.u64(),
  updatedAt: __t.u64(),
});
export type ScanSession = __Infer<typeof ScanSession>;

export const UserProfile = __t.object("UserProfile", {
  accountId: __t.string(),
  username: __t.string(),
  email: __t.string(),
  lastSeen: __t.u64(),
});
export type UserProfile = __Infer<typeof UserProfile>;

