// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  id: __t.string(),
  sessionId: __t.string(),
  scanArtifactId: __t.string(),
  catalogCardId: __t.string(),
  canonicalCardId: __t.string(),
  oracleId: __t.string(),
  name: __t.string(),
  setCode: __t.string(),
  collectorNumber: __t.string(),
  imageUri: __t.string(),
  similarityScore: __t.u32(),
  ocrScore: __t.u32(),
  finalScore: __t.u32(),
  matchReason: __t.string(),
  finish: __t.string(),
  condition: __t.string(),
  quantity: __t.u32(),
};
