// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddToDeckReducer from "../add_to_deck_reducer";
import AddToInventoryReducer from "../add_to_inventory_reducer";
import CreateDeckReducer from "../create_deck_reducer";
import DeleteDeckReducer from "../delete_deck_reducer";
import EnsureInventoryReducer from "../ensure_inventory_reducer";
import RemoveFromDeckReducer from "../remove_from_deck_reducer";
import RemoveFromInventoryReducer from "../remove_from_inventory_reducer";
import ReorderInventoryCardReducer from "../reorder_inventory_card_reducer";
import UpdateDeckReducer from "../update_deck_reducer";
import UpdateDeckCardReducer from "../update_deck_card_reducer";
import UpdateInventoryCardReducer from "../update_inventory_card_reducer";

export type AddToDeckParams = __Infer<typeof AddToDeckReducer>;
export type AddToInventoryParams = __Infer<typeof AddToInventoryReducer>;
export type CreateDeckParams = __Infer<typeof CreateDeckReducer>;
export type DeleteDeckParams = __Infer<typeof DeleteDeckReducer>;
export type EnsureInventoryParams = __Infer<typeof EnsureInventoryReducer>;
export type RemoveFromDeckParams = __Infer<typeof RemoveFromDeckReducer>;
export type RemoveFromInventoryParams = __Infer<typeof RemoveFromInventoryReducer>;
export type ReorderInventoryCardParams = __Infer<typeof ReorderInventoryCardReducer>;
export type UpdateDeckParams = __Infer<typeof UpdateDeckReducer>;
export type UpdateDeckCardParams = __Infer<typeof UpdateDeckCardReducer>;
export type UpdateInventoryCardParams = __Infer<typeof UpdateInventoryCardReducer>;

