// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddToCollectionReducer from "../add_to_collection_reducer";
import ConnectUserReducer from "../connect_user_reducer";
import CreateCollectionReducer from "../create_collection_reducer";
import DeleteCollectionReducer from "../delete_collection_reducer";
import RemoveFromCollectionReducer from "../remove_from_collection_reducer";
import UpdateCollectionReducer from "../update_collection_reducer";
import UpdateCollectionCardReducer from "../update_collection_card_reducer";

export type AddToCollectionParams = __Infer<typeof AddToCollectionReducer>;
export type ConnectUserParams = __Infer<typeof ConnectUserReducer>;
export type CreateCollectionParams = __Infer<typeof CreateCollectionReducer>;
export type DeleteCollectionParams = __Infer<typeof DeleteCollectionReducer>;
export type RemoveFromCollectionParams = __Infer<typeof RemoveFromCollectionReducer>;
export type UpdateCollectionParams = __Infer<typeof UpdateCollectionReducer>;
export type UpdateCollectionCardParams = __Infer<typeof UpdateCollectionCardReducer>;

