import { schema, table, t } from 'spacetimedb/server';

// --- Tables ---

const userProfile = table(
  { name: 'user_profile', public: true },
  {
    accountId: t.string().primaryKey(),    // Pangolin Remote-Subject UUID
    username: t.string(),                   // Remote-User, synced on connect
    email: t.string(),                      // Remote-Email, synced on connect
    lastSeen: t.u64(),                      // Unix timestamp microseconds
  }
);

const serverConfig = table(
  { name: 'server_config', public: false },
  {
    key: t.string().primaryKey(),           // e.g. "auth_signing_secret"
    value: t.string(),
  }
);

const collection = table(
  {
    name: 'collection',
    public: true,
    indexes: [{ accessor: 'collection_owner_id', algorithm: 'btree', columns: ['ownerId'] }],
  },
  {
    id: t.string().primaryKey(),            // UUID generated by reducer
    ownerId: t.string(),                    // FK to userProfile.accountId
    name: t.string(),
    description: t.string(),
    createdAt: t.u64(),                     // Unix timestamp microseconds
  }
);

const collectionCard = table(
  {
    name: 'collection_card',
    public: true,
    indexes: [{ accessor: 'collection_card_collection_id', algorithm: 'btree', columns: ['collectionId'] }],
  },
  {
    // Synthetic compound key: "${collectionId}_${scryfallId}_${isFoil}_${condition}"
    compositeId: t.string().primaryKey(),
    collectionId: t.string(),               // FK to collection.id
    scryfallId: t.string(),                 // Exact printing reference
    oracleId: t.string(),                   // Groups "same card" across printings
    name: t.string(),                       // Denormalized for display
    setCode: t.string(),                    // Denormalized for display
    imageUri: t.string(),                   // Denormalized, snapshot at add-time
    quantity: t.u32(),
    isFoil: t.bool(),
    condition: t.string(),                  // "NM" | "LP" | "MP" | "HP" | "DMG"
    notes: t.string(),
    addedAt: t.u64(),                       // Unix timestamp microseconds
    updatedAt: t.u64(),                     // Unix timestamp microseconds
  }
);

// --- Schema export ---

const spacetimedb = schema({
  userProfile,
  serverConfig,
  collection,
  collectionCard,
});

export default spacetimedb;
